from daliy_copy_task import copy_by_mapping

tasks = [
    # 累計客戶數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A1",
        "src_date_cell": "B1",
        "src_value_range": "B2:B25",
        "dst_key_cell": "A1",
        "dst_date_row": 2,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝申請數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A28",
        "src_date_cell": "B28",
        "src_value_range": "B29:B52",
        "dst_key_cell": "A55",
        "dst_date_row": 56,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝竣工數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A55",
        "src_date_cell": "B55",
        "src_value_range": "B56:B79",
        "dst_key_cell": "A82",
        "dst_date_row": 83,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租申請數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A82",
        "src_date_cell": "B82",
        "src_value_range": "B83:B106",
        "dst_key_cell": "A109",
        "dst_date_row": 110,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租竣工數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A109",
        "src_date_cell": "B109",
        "src_value_range": "B110:B133",
        "dst_key_cell": "A136",
        "dst_date_row": 137,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝註銷數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A136",
        "src_date_cell": "B136",
        "src_value_range": "B137:B160",
        "dst_key_cell": "A163",
        "dst_date_row": 164,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 累計客戶數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A163",
        "src_date_cell": "B163",
        "src_value_range": "B164:B187",
        "dst_key_cell": "A190",
        "dst_date_row": 191,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝申請數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A190",
        "src_date_cell": "B190",
        "src_value_range": "B191:B214",
        "dst_key_cell": "A244",
        "dst_date_row": 245,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝竣工數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A217",
        "src_date_cell": "B217",
        "src_value_range": "B218:B241",
        "dst_key_cell": "A271",
        "dst_date_row": 272,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租申請數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A244",
        "src_date_cell": "B244",
        "src_value_range": "B245:B268",
        "dst_key_cell": "A298",
        "dst_date_row": 299,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租竣工數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A271",
        "src_date_cell": "B271",
        "src_value_range": "B272:B295",
        "dst_key_cell": "A325",
        "dst_date_row": 326,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝註銷數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "日統計",
        "src_key_cell": "A298",
        "src_date_cell": "B298",
        "src_value_range": "B299:B322",
        "dst_key_cell": "A352",
        "dst_date_row": 353,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },

    ########無上網########
     # 累計客戶數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A1",
        "src_date_cell": "B1",
        "src_value_range": "B2:B25",
        "dst_key_cell": "A1",
        "dst_date_row": 2,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝申請數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A28",
        "src_date_cell": "B28",
        "src_value_range": "B29:B52",
        "dst_key_cell": "A55",
        "dst_date_row": 56,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝竣工數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A55",
        "src_date_cell": "B55",
        "src_value_range": "B56:B79",
        "dst_key_cell": "A82",
        "dst_date_row": 83,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租申請數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A82",
        "src_date_cell": "B82",
        "src_value_range": "B83:B106",
        "dst_key_cell": "A109",
        "dst_date_row": 110,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租竣工數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A109",
        "src_date_cell": "B109",
        "src_value_range": "B110:B133",
        "dst_key_cell": "A136",
        "dst_date_row": 137,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝註銷數(ALL)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A136",
        "src_date_cell": "B136",
        "src_value_range": "B137:B160",
        "dst_key_cell": "A163",
        "dst_date_row": 164,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 累計客戶數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A163",
        "src_date_cell": "B163",
        "src_value_range": "B164:B187",
        "dst_key_cell": "A190",
        "dst_date_row": 191,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝申請數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A190",
        "src_date_cell": "B190",
        "src_value_range": "B191:B214",
        "dst_key_cell": "A244",
        "dst_date_row": 245,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝竣工數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A217",
        "src_date_cell": "B217",
        "src_value_range": "B218:B241",
        "dst_key_cell": "A271",
        "dst_date_row": 272,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租申請數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A244",
        "src_date_cell": "B244",
        "src_value_range": "B245:B268",
        "dst_key_cell": "A298",
        "dst_date_row": 299,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 退租竣工數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A271",
        "src_date_cell": "B271",
        "src_value_range": "B272:B295",
        "dst_key_cell": "A325",
        "dst_date_row": 326,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
    # 新裝註銷數(消客)
    {
        "src_file": "114年dailyTool-單日",
        "src_sheet": "無上網日統計模板",
        "dst_prefix": "影視業務日報表",
        "dst_sheet": "無上網日統計",
        "src_key_cell": "A298",
        "src_date_cell": "B298",
        "src_value_range": "B299:B322",
        "dst_key_cell": "A352",
        "dst_date_row": 353,
        "dst_value_start_offset_row": 1,
        "dst_value_start_offset_col": 0,
    },
]

copy_by_mapping(tasks)
