# run_dailyCopy_2.py
import daliy_copy_task

# 🔑 新增參數 target_date=None
def run_step(wb_src, wb_dst, target_date=None):
    """
    Step 2 主程式
    """

    tasks = [
        # ... (這裡保留你原本那一大串 tasks 設定，不用動) ...
        # 為了節省版面，請保留你原本的 tasks 列表內容
        # 累計客戶數(ALL)
        {
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A1",
            "src_date_cell": "B1",
            "src_value_range": "B2:B25",
            "dst_key_cell": "A1",
            "dst_date_row": 2,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        # ... (以下請保留原本所有任務) ...
        { # 新裝申請數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A28",
            "src_date_cell": "B28",
            "src_value_range": "B29:B52",
            "dst_key_cell": "A55",
            "dst_date_row": 56,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 新裝竣工數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A55",
            "src_date_cell": "B55",
            "src_value_range": "B56:B79",
            "dst_key_cell": "A82",
            "dst_date_row": 83,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 新裝註銷數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A82",
            "src_date_cell": "B82",
            "src_value_range": "B83:B106",
            "dst_key_cell": "A109",
            "dst_date_row": 110,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機申請數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A109",
            "src_date_cell": "B109",
            "src_value_range": "B110:B133",
            "dst_key_cell": "A136",
            "dst_date_row": 137,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機竣工數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A136",
            "src_date_cell": "B136",
            "src_value_range": "B137:B160",
            "dst_key_cell": "A163",
            "dst_date_row": 164,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機註銷數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A163",
            "src_date_cell": "B163",
            "src_value_range": "B164:B187",
            "dst_key_cell": "A190",
            "dst_date_row": 191,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 異動申請數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A190",
            "src_date_cell": "B190",
            "src_value_range": "B191:B214",
            "dst_key_cell": "A217",
            "dst_date_row": 218,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 異動竣工數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A217",
            "src_date_cell": "B217",
            "src_value_range": "B218:B241",
            "dst_key_cell": "A244",
            "dst_date_row": 245,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 異動註銷數
            "src_file": "114年dailyTool-單日",
            "src_sheet": "日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "日統計",
            "src_key_cell": "A244",
            "src_date_cell": "B244",
            "src_value_range": "B245:B268",
            "dst_key_cell": "A271",
            "dst_date_row": 272,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },

        # --- (消客) 系列 ---
        { # 累計客戶數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A1",
            "src_date_cell": "B1",
            "src_value_range": "B2:B25",
            "dst_key_cell": "A1",
            "dst_date_row": 2,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 新裝申請數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A28",
            "src_date_cell": "B28",
            "src_value_range": "B29:B52",
            "dst_key_cell": "A28",
            "dst_date_row": 29,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 新裝竣工數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A55",
            "src_date_cell": "B55",
            "src_value_range": "B56:B79",
            "dst_key_cell": "A55",
            "dst_date_row": 56,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 新裝註銷數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A82",
            "src_date_cell": "B82",
            "src_value_range": "B83:B106",
            "dst_key_cell": "A82",
            "dst_date_row": 83,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機申請數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A109",
            "src_date_cell": "B109",
            "src_value_range": "B110:B133",
            "dst_key_cell": "A109",
            "dst_date_row": 110,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機竣工數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A136",
            "src_date_cell": "B136",
            "src_value_range": "B137:B160",
            "dst_key_cell": "A136",
            "dst_date_row": 137,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 拆機註銷數(消客)
            "src_file": "114年dailyTool-單日",
            "src_sheet": "無上網日統計模板",
            "dst_prefix": "影視業務日報表",
            "dst_sheet": "無上網日統計",
            "src_key_cell": "A163",
            "src_date_cell": "B163",
            "src_value_range": "B164:B187",
            "dst_key_cell": "A163",
            "dst_date_row": 164,
            "dst_value_start_offset_row": 1,
            "dst_value_start_offset_col": 0,
        },
        { # 異動申請數(消客)